--REPLACE MZPL_B
BEGIN
    rdsadmin.rdsadmin_util.create_directory(p_directory_name => 'MZPL_B_FILES');
END; 


CREATE USER MZPL_B
IDENTIFIED BY MZPL_B
DEFAULT TABLESPACE SEA_TB_MISC
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
ACCOUNT UNLOCK;
GRANT CONNECT TO MZPL_B;
GRANT SELECT_CATALOG_ROLE TO MZPL_B WITH ADMIN OPTION;
ALTER USER MZPL_B DEFAULT ROLE ALL;
GRANT ALTER ANY PROCEDURE TO MZPL_B;
GRANT CREATE ANY CONTEXT TO MZPL_B;
GRANT CREATE ANY MATERIALIZED VIEW TO MZPL_B;
GRANT CREATE ANY PROCEDURE TO MZPL_B;
GRANT CREATE ANY SEQUENCE TO MZPL_B;
GRANT CREATE ANY TABLE TO MZPL_B;
GRANT CREATE ANY TYPE TO MZPL_B;
GRANT CREATE ANY VIEW TO MZPL_B;
GRANT CREATE VIEW TO MZPL_B;
GRANT DROP ANY CONTEXT TO MZPL_B;
GRANT DROP ANY MATERIALIZED VIEW TO MZPL_B;
GRANT DROP ANY VIEW TO MZPL_B;
GRANT UNLIMITED TABLESPACE TO MZPL_B;
GRANT EXECUTE ON RDSADMIN.RDSADMIN_S3_TASKS TO MZPL_B;
GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO MZPL_B;
GRANT READ, WRITE ON DIRECTORY MZPL_B_FILES TO MZPL_B;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO MZPL_B;
GRANT EXECUTE ON SYS.DBMS_DATAPUMP TO MZPL_B;
GRANT EXECUTE ON SYS.DBMS_FILE_TRANSFER TO MZPL_B;
GRANT EXECUTE ON SYS.DBMS_XMLGEN TO MZPL_B;
GRANT SELECT ON SYS.V_$SESSION TO MZPL_B WITH GRANT OPTION;
GRANT EXECUTE ON XDB.DBMS_XMLDOM TO MZPL_B;
GRANT EXECUTE ON ADMIN.WM_CONCAT TO MZPL_B;
GRANT ALTER ANY TRIGGER TO MZPL_B;
GRANT CREATE ANY TRIGGER TO MZPL_B;
GRANT DROP ANY TRIGGER TO MZPL_B;
GRANT EXECUTE ON rdsadmin.rds_file_util TO MZPL_B;
GRANT READ ON DIRECTORY BDUMP TO MZPL_B;
grant execute on P_DELETE_TEMP_REPLICA to admin;

begin 
    rdsadmin.rdsadmin_util.grant_sys_object( p_obj_name => 'DBMS_XMLSAVE', p_grantee => 'MZPL_B', p_privilege => 'EXECUTE', p_grant_option => true); 
    rdsadmin.rdsadmin_util.grant_sys_object( p_obj_name => 'DBMS_XMLSTORE', p_grantee => 'MZPL_B', p_privilege => 'EXECUTE', p_grant_option => true); 
    rdsadmin.rdsadmin_util.grant_sys_object( p_obj_name => 'DBMS_XMLQUERY', p_grantee => 'MZPL_B', p_privilege => 'EXECUTE', p_grant_option => true); 
    rdsadmin.rdsadmin_util.grant_sys_object( p_obj_name => 'DBMS_SESSION', p_grantee => 'MZPL_B', p_privilege => 'EXECUTE', p_grant_option => true); 
end;
