--[BUCKETUSER] WITH FILDER NAME CRATED IN S3 BUCKET
--[DBUSER] SCHEMA NAME



UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = 'https://files.synergicserp.com/[BUCKETUSER]/FILES/' WHERE CONFIG_ID = 16;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = 'https://temp.synergicserp.com/[BUCKETUSER]/' WHERE CONFIG_ID = 32;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = 'https://app.synergicserp.com/[BUCKETUSER]/Default.aspx' WHERE CONFIG_ID = 51;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = 'https://files.synergicserp.com/[BUCKETUSER]/IMAGES/' WHERE CONFIG_ID = 1;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = 'https://files.synergicserp.com/[BUCKETUSER]/' WHERE CONFIG_ID = 7;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = 'http://files.synergicserp.com/[BUCKETUSER]/IMAGES/' WHERE CONFIG_ID = 49;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = 'https://files.synergicserp.com/[BUCKETUSER]/FILES/' WHERE CONFIG_ID = 19;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = 'https://files.synergicserp.com/[BUCKETUSER]/IMAGES/' WHERE CONFIG_ID = 168;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = 'https://app.synergicserp.com/[BUCKETUSER]/Reports.aspx' WHERE CONFIG_ID = 228;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = 'https://app.synergicserp.com/[BUCKETUSER]/' WHERE CONFIG_ID = 266;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = 'http://files.synergicserp.com/[BUCKETUSER]/IMAGES/' WHERE CONFIG_ID = 284;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = 'https://app.synergicserp.com/[BUCKETUSER]/' WHERE CONFIG_ID = 325;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = 'https://app.synergicserp.com/[BUCKETUSER]/Temprdlc/' WHERE CONFIG_ID = 430;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = 'http://files.synergicserp.com/[BUCKETUSER]/IMAGES/' WHERE CONFIG_ID = 591;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = 'https://files.synergicserp.com/[BUCKETUSER]/FILES/' WHERE CONFIG_ID = 621;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = 'sspl-client/[BUCKETUSER]' WHERE CONFIG_ID = 728;
UPDATE T_CONFIG_GLOBAL SET CONFIG_REMARKS = NULL,CONFIG_VALUE = 'sspl-client-temp/[BUCKETUSER]' WHERE CONFIG_ID = 729;
UPDATE T_CONFIG_GLOBAL SET CONFIG_REMARKS = NULL,CONFIG_VALUE = 'sspl-client/[BUCKETUSER]/IMAGES' WHERE CONFIG_ID = 730;
UPDATE T_CONFIG_GLOBAL SET CONFIG_REMARKS = NULL,CONFIG_VALUE = 'sspl-client/[BUCKETUSER]/FILES' WHERE CONFIG_ID = 731;
UPDATE T_CONFIG_GLOBAL SET CONFIG_REMARKS = NULL,CONFIG_VALUE = 'sspl-client-temp/[BUCKETUSER]' WHERE CONFIG_ID = 732;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = 'C:\AppFolder\[DBUSER]\Temprdlc\' WHERE CONFIG_ID = 429;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = 'https://app.synergicserp.com/[DBUSER]/Temprdlc/' WHERE CONFIG_ID = 430;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = 'C:\AppFolder\[DBUSER]\Reports\' WHERE CONFIG_ID = 435;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = '1' WHERE CONFIG_ID = 458;

COMMIT;

UPDATE T_AUTH_EMPLOYEE_MASTER SET LOGIN_PWD = F_MANAGE_PASS('Encrypt',LOGIN_NAME,'SEA.NET.') WHERE LOGIN_NAME is not null;

--=======================

UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = '[DBUSER]_FILES' WHERE CONFIG_ID = 34;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = '[DBUSER]_FILES' WHERE CONFIG_ID = 24;
UPDATE T_CONFIG_GLOBAL SET CONFIG_VALUE = '[DBUSER]_FILES' WHERE CONFIG_ID = 23;

CREATE OR REPLACE CONTEXT SEA[DBUSER] USING P_SEANET_CONTEXT;
COMMIT;

GRANT EXECUTE ON SYS.DBMS_CRYPTO TO [DBUSER];