select t.table_name
from sys.user_tables t
left join sys.user_constraints c
          on t.table_name = c.table_name
          and c.constraint_type = 'P'
where c.constraint_type is null
AND T.TABLE_NAME IN (
'T_CUSTOM_ITEM_ATTRIB_DTL','T_CUSTOM_ITEM_MASTER','T_CUSTOM_STOCK','T_CUSTOM_STOCK_DTL','T_DAILY_TRANS','T_DAILY_TRANS_ALL','T_DAILY_TRANS_ALL_FORMULA','T_DAILY_TRANS_CUSTOMER','T_DAILY_TRANS_MFGR','T_DAILY_TRANS_MFGR_BOM',
'T_DAILY_TRANS_MFGR_INOUT','T_DAILY_TRANS_MFGR_LOSS','T_DAILY_TRANS_MFGR_SCRAP','T_DAILY_TRANS_ORDER','T_DAILY_TRANS_ORDER_BOM','T_DAILY_TRANS_OTHER','T_DAILY_TRANS_OTHER_BOM','T_DAILY_TRANS_PRODUCTION',
'T_DAILY_TRANS_PRODUCTION_BOM','T_DAILY_TRANS_PURCHASE','T_DAILY_TRANS_PURCHASE_BOM','T_DAILY_TRANS_SALES','T_DAILY_TRANS_SALES_BOM','T_DAILY_TRANS_TRANSFER','T_DAILY_TRANS_TRANSFER_BOM','T_FA_ACCOUNT_CL_BAL',
'T_FA_ACCOUNT_MASTER','T_FA_ACCOUNT_MASTER_DTL','T_FA_ACCOUNT_MASTER_EXTD','T_FA_BANK_ACCOUNT_MASTER','T_FA_BANK_BRANCH_MASTER','T_FA_BANK_MASTER','T_FA_BILL_RESERVATION','T_FA_COSTCENTER_MASTER','T_FA_DAILY_CL_STOCK',
'T_FA_TRANS_BILL_HDR','T_FA_TRANS_BILL_HDR_EXTD','T_FA_TRANS_COSTCENTER_DTL','T_FA_TRANS_DTL','T_FA_TRANS_HDR','T_FA_TRANS_HDR_OTHERS','T_FA_TRANS_RECPAY_ADJ','T_FA_TRANS_RECPAY_DTL','T_FA_TRANS_RECPAY_HDR','T_FA_TRANS_SMRY',
'T_FA_TRANS_TDS_DTL','T_FORMULA_BULLION_RATE','T_FORMULA_PROCEDURE_DTL','T_FORMULA_PROCEDURE_MAPPING','T_FORMULA_PROCEDURE_MASTER','T_ITEM_ATTRIB_MASTER','T_ITEM_ATTRIB_MASTER_EXTD','T_ITEM_EXCLUSIVITY_DTL',
'T_ITEM_EXCLUSIVITY_MASTER','T_ITEM_LINK','T_ITEM_MASTER','T_ITEM_MASTER_ATTRIB_DTL','T_ITEM_MASTER_EXTD','T_ITEM_RESTRICTION_LIST','T_ITEM_VARIANT_ATTRIB_DTL','T_ITEM_VARIANT_ATTRIB_LIST','T_ITEM_VARIANT_BOM_DTL',
'T_ITEM_VARIANT_IMAGE_DTL','T_ITEM_VARIANT_LINK','T_ITEM_VARIANT_MASTER','T_ITEM_VARIANT_MASTER_EXTD','T_ITEM_VARIANT_OPERATION_DTL','T_ITEM_VARIANT_PD','T_MISC_ADDRESS_DTL','T_MISC_ADDRESS_MASTER','T_MISC_COMMON_DATA_MASTER',
'T_MISC_TERMS_MASTER','T_MISC_TERMS_SPLIT_DTL','T_OPERATION_MASTER','T_OPERATION_QC_MASTER','T_OPERATION_ROUTING_DTL','T_OPERATION_ROUTING_MASTER','T_PARTY_CONTACT_MASTER','T_PARTY_LOCATION_MAPPING','T_PARTY_MAPPING_DTL',
'T_PARTY_MASTER','T_PARTY_MASTER_ATTACHMENT','T_PARTY_MASTER_EXTD','T_PARTY_MISC_LINK','T_PD_ORDER_STATUS','T_SCHEME_MASTER','T_SCHEME_PARTY_LINK_DTL','T_SCHEME_PARTY_LINK_HDR','T_SESSION_ACTIVITY','T_SESSION_INFO',
'T_SMRY_CUSTOMER_STOCK','T_SMRY_ITEM_MASTER','T_SMRY_ITEM_MASTER_ATTRIB','T_SMRY_ITEM_VARIANT_ATTRIB','T_SMRY_ITEM_VARIANT_BOM','T_SMRY_ITEM_VARIANT_METAL','T_SMRY_ITEM_VARIANT_STONE','T_SMRY_STOCK_BOM',
'T_SMRY_STOCK_DAILY_CLOSING','T_SMRY_TRANS_ITEM_BOM','T_STATUS_OF_TRANS_ITEM','T_STOCK','T_STOCK_ADDITIONAL_DTL','T_STOCK_ARCHIVE','T_STOCK_ATTRIB_DTL','T_STOCK_ATTRIB_SMRY','T_STOCK_BATCH_DTL','T_STOCK_BATCH_MISC_INFO',
'T_STOCK_BATCH_PERFORMED_OPN','T_STOCK_BATCH_PPC_DTL','T_STOCK_BATCH_ROUTING_DTL','T_STOCK_BATCH_TRANS_LINK','T_STOCK_BOM_ATTRIB_DTL','T_STOCK_BOM_ATTRIB_SMRY','T_STOCK_BOM_CERTIFICATE_DTL','T_STOCK_BOM_DTL',
'T_STOCK_BOM_LOCATION_SP','T_STOCK_BOM_LOCATION_SP_DTL','T_STOCK_BOM_OPERATION_DTL','T_STOCK_BOM_TRANS_LINK','T_STOCK_CERTIFICATE_DTL','T_STOCK_CODE_MISC_DTL','T_STOCK_DTL','T_STOCK_GROUP','T_STOCK_IN_OUT_DTL',
'T_STOCK_IN_OUT_DTL_ADDN','T_STOCK_LOCATION_SP','T_STOCK_LOCATION_SP_DTL','T_STOCK_MISC_INFO','T_STOCK_QC_DTL','T_STOCK_SCRAP_COLLECTION_DTL','T_STOCK_SCRAP_COLLECTION_HDR','T_STOCK_SOURCE_BATCH_DTL','T_STOCK_TRANS_LINK',
'T_TRANS_FORMULA_DTL','T_TRANS_HDR','T_TRANS_HDR_ATTACHMENT','T_TRANS_HDR_DISPATCH_DTL','T_TRANS_HDR_EXTD','T_TRANS_HDR_IMPEXP','T_TRANS_HDR_OTHERS','T_TRANS_HDR_SHIPMENT','T_TRANS_ITEM_ATTRIB_DTL','T_TRANS_ITEM_BOM_ATTRIB_DTL',
'T_TRANS_ITEM_BOM_DTL','T_TRANS_ITEM_BOM_DTL_EXTD','T_TRANS_ITEM_BOM_DTL_MISC','T_TRANS_ITEM_BOM_FORMULA_DTL','T_TRANS_ITEM_DTL','T_TRANS_ITEM_DTL_ATTACHMENT','T_TRANS_ITEM_DTL_EXTD','T_TRANS_ITEM_DTL_MISC',
'T_TRANS_ITEM_FORMULA_DTL','T_TRANS_ITEM_FORMULA_SCHEME','T_TRANS_ITEM_MISC_INFO','T_TRANS_ITEM_MISC_INFO_DTL','T_TRANS_ITEM_OPERATION_DTL','T_TRANS_ITEM_OPN_FORMULA_DTL','T_TRANS_ITEM_OTHER_ITEM_DTL','T_TRANS_ITEM_QC_DTL',
'T_TRANS_ITEM_REF_DTL','T_TRANS_ITEM_REMARK_DTL','T_TRANS_ITEM_SERVICING_DTL','T_TRANS_MFG_LOSS_DTL','T_TRANS_MFG_WC_STOCK_DTL','T_TRANS_REF_ISSUE','T_VA_TRANS_ATTRIB_DTL','T_VA_TRANS_CUSTOM_DTL','T_VA_TRANS_DTL',
'T_VA_TRANS_HDR','T_VERIFICATION_SMRY','T_WORKCENTER_GROUP_MASTER','T_WORKCENTER_MASTER','T_SMRY_STOCK_MONTH_CLOSING','T_TRANS_ITEM_MISC_INFO'
)
order by t.table_name;



