ALTER TABLE T_DAILY_TRANS_ALL_FORMULA ADD CONSTRAINT PK_DTAF_TIID PRIMARY KEY(TRANS_ITEM_ID);

ALTER TABLE T_DAILY_TRANS_MFGR_LOSS ADD PK_ID VARCHAR2(150);
UPDATE T_DAILY_TRANS_MFGR_LOSS SET PK_ID = SYS_GUID();
COMMIT;
ALTER TABLE T_DAILY_TRANS_MFGR_LOSS ADD CONSTRAINT PK_DTML_PKID PRIMARY KEY(PK_ID);

ALTER TABLE T_DAILY_TRANS_MFGR_SCRAP ADD PK_ID VARCHAR2(150);
UPDATE T_DAILY_TRANS_MFGR_SCRAP SET PK_ID = SYS_GUID();
COMMIT;
ALTER TABLE T_DAILY_TRANS_MFGR_SCRAP ADD CONSTRAINT PK_DTMS_PKID PRIMARY KEY(PK_ID);

ALTER TABLE T_MISC_ADDRESS_DTL DROP CONSTRAINT UNQ_ADDID;
ALTER TABLE T_MISC_ADDRESS_DTL ADD CONSTRAINT PK_MIADDTL_ADDID PRIMARY KEY(ADDRESS_ID);

ALTER TABLE T_SMRY_STOCK_MONTH_CLOSING ADD CONSTRAINT PK_SSMC PRIMARY KEY(PK_ID);

ALTER TABLE T_DAILY_TRANS_CUSTOMER ADD CONSTRAINT PK_DTC PRIMARY KEY(TRANS_ITEM_ID);

ALTER TABLE T_DAILY_TRANS_FORMULA ADD CONSTRAINT PK_DTF_TIID PRIMARY KEY(TRANS_ITEM_ID);

ALTER TABLE T_DAILY_TRANS_MFGR ADD CONSTRAINT PK_DTMFGR PRIMARY KEY(TRANS_ITEM_ID);

ALTER TABLE T_DAILY_TRANS_MFGR_BOM ADD CONSTRAINT PK_DTMFGRBOM PRIMARY KEY(TRANS_ITEM_BOM_ID);

ALTER TABLE T_DAILY_TRANS_ORDER ADD CONSTRAINT PK_DTO PRIMARY KEY(TRANS_ITEM_ID);

ALTER TABLE T_DAILY_TRANS_ORDER_BOM ADD CONSTRAINT PK_DTOB PRIMARY KEY(TRANS_ITEM_BOM_ID);

ALTER TABLE T_DAILY_TRANS_PURCHASE ADD CONSTRAINT PK_DTPUR PRIMARY KEY(TRANS_ITEM_ID);

ALTER TABLE T_DAILY_TRANS_PURCHASE_BOM ADD CONSTRAINT PK_DTPURB PRIMARY KEY(TRANS_ITEM_BOM_ID);

ALTER TABLE T_DAILY_TRANS_SALES ADD CONSTRAINT PK_DTS PRIMARY KEY(TRANS_ITEM_ID);

ALTER TABLE T_DAILY_TRANS_SALES_BOM ADD CONSTRAINT PK_DTSB PRIMARY KEY(TRANS_ITEM_BOM_ID);

ALTER TABLE T_TRANS_ITEM_MISC_INFO ADD PK_ID NUMBER(10);
CREATE SEQUENCE TRANS_ITEM_MISC_INFO START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE ORDER;
UPDATE T_TRANS_ITEM_MISC_INFO SET PK_ID = TRANS_ITEM_MISC_INFO.NEXTVAL;
COMMIT;
ALTER TABLE T_TRANS_ITEM_MISC_INFO ADD CONSTRAINT PK_TRANS_ITEM_MISC_INFO PRIMARY KEY(PK_ID);
