-- IMPORT USER
-- REPLACE [DBUSER]
-- REPLACE [OLDUSER]
-- REPLACE [FILE_NAME]

DECLARE
    hdnl NUMBER;
BEGIN
    hdnl := DBMS_DATAPUMP.OPEN( operation => 'IMPORT', job_mode => 'SCHEMA', job_name=>null);
    DBMS_DATAPUMP.ADD_FILE( handle => hdnl, filename => '[FILE_NAME].DMP', directory => 'DATA_PUMP_DIR', filetype => dbms_datapump.ku$_file_type_dump_file);
    DBMS_DATAPUMP.ADD_FILE( handle => hdnl, filename => '[FILE_NAME].log', directory => 'DATA_PUMP_DIR', filetype => dbms_datapump.ku$_file_type_log_file);
--  DBMS_DATAPUMP.METADATA_REMAP(hdnl,'REMAP_TABLESPACE','ARCH_DATA','SEA_TB_MISC');
--  DBMS_DATAPUMP.METADATA_REMAP(hdnl,'REMAP_TABLESPACE','ARCH_INDX','SEA_TB_INDX_MISC');
--  DBMS_DATAPUMP.METADATA_REMAP(hdnl,'REMAP_TABLESPACE','DATA_GROUP_1','LIVE_DATA_4');
--  DBMS_DATAPUMP.METADATA_REMAP(hdnl,'REMAP_TABLESPACE','DATA_GROUP_2','LIVE_DATA_4');
--  DBMS_DATAPUMP.METADATA_REMAP(hdnl,'REMAP_TABLESPACE','DATA_GROUP_3','LIVE_DATA_4');
--  DBMS_DATAPUMP.METADATA_REMAP(hdnl,'REMAP_TABLESPACE','DATA_GROUP_4','LIVE_DATA_4');
--  DBMS_DATAPUMP.METADATA_REMAP(hdnl,'REMAP_TABLESPACE','DATA_GROUP_5','LIVE_DATA_5');
--  DBMS_DATAPUMP.METADATA_REMAP(hdnl,'REMAP_TABLESPACE','DNETLIVE_DATA_MISC','SEA_TB_MISC');
--  DBMS_DATAPUMP.METADATA_REMAP(hdnl,'REMAP_TABLESPACE','SEA_TB_INDX_ITEM','SEA_TB_INDX_MISC');
--  DBMS_DATAPUMP.METADATA_REMAP(hdnl,'REMAP_TABLESPACE','SEA_TB_LOB','SEA_TB_MISC');
--  DBMS_DATAPUMP.METADATA_REMAP(hdnl,'REMAP_TABLESPACE','SEA_TB_VA','SEA_TB_MISC');
    DBMS_DATAPUMP.METADATA_REMAP(hdnl,'REMAP_SCHEMA','[OLDUSER]','[DBUSER]');
    DBMS_DATAPUMP.METADATA_FILTER(hdnl,'SCHEMA_EXPR','IN (''[OLDUSER]'')');
    DBMS_DATAPUMP.START_JOB(hdnl);
END;
/         


/*

SELECT TEXT,CNT
FROM (
    SELECT text,ROWNUM AS CNT FROM table(rdsadmin.rds_file_util.read_text_file('DATA_PUMP_DIR','[FILE_NAME].log'))
)
ORDER BY CNT DESC

*/