DELETE FROM T_CONFIG_CLIENT_MASTER;
DELETE FROM T_CONFIG_FILTER_MASTER;
DELETE FROM T_CONFIG_FILTER_MAPPING;
DELETE FROM T_CONFIG_QUERY_SETTING;
DELETE FROM T_CONFIG_QUERY_DATA;
DELETE FROM T_DASHBOARD_CONFIG;
DELETE FROM T_REPORT_CUSTOMER_MAPPING;
DELETE FROM T_REPORT_FILTER_MAPPING;
DELETE FROM T_REPORT_VOUCHER_MAPPING;
DELETE FROM T_REPORT_CHILD_QUERY_DTL;
DELETE FROM T_REPORT_CHILD_CONFIG;
DELETE FROM T_REPORT_QUERY_DTL;
DELETE FROM T_REPORT_CONFIG;
DELETE FROM T_REPORT_FILTER_DTL;
DELETE FROM T_REPORT_FILTER_HDR;
DELETE FROM T_REPORT_CONFIG_QUERY_SETTING;
DELETE FROM T_CONFIG_TAG;



INSERT INTO T_CONFIG_CLIENT_MASTER SELECT * FROM T_CONFIG_CLIENT_MASTER@DNET_LINK;
INSERT INTO T_CONFIG_FILTER_MASTER SELECT * FROM T_CONFIG_FILTER_MASTER@DNET_LINK;
INSERT INTO T_CONFIG_FILTER_MAPPING SELECT * FROM T_CONFIG_FILTER_MAPPING@DNET_LINK;
INSERT INTO T_CONFIG_QUERY_DATA SELECT * FROM T_CONFIG_QUERY_DATA@DNET_LINK;
INSERT INTO T_CONFIG_QUERY_SETTING SELECT * FROM T_CONFIG_QUERY_SETTING@DNET_LINK;
INSERT INTO T_DASHBOARD_CONFIG SELECT * FROM T_DASHBOARD_CONFIG@DNET_LINK;
INSERT INTO T_REPORT_CUSTOMER_MAPPING SELECT * FROM T_REPORT_CUSTOMER_MAPPING@DNET_LINK;
INSERT INTO T_REPORT_FILTER_MAPPING SELECT * FROM T_REPORT_FILTER_MAPPING@DNET_LINK;
INSERT INTO T_REPORT_VOUCHER_MAPPING SELECT * FROM T_REPORT_VOUCHER_MAPPING@DNET_LINK;
INSERT INTO T_REPORT_CHILD_QUERY_DTL SELECT * FROM T_REPORT_CHILD_QUERY_DTL@DNET_LINK;
INSERT INTO T_REPORT_CHILD_CONFIG SELECT * FROM T_REPORT_CHILD_CONFIG@DNET_LINK;
INSERT INTO T_REPORT_QUERY_DTL SELECT * FROM T_REPORT_QUERY_DTL@DNET_LINK;
INSERT INTO T_REPORT_CONFIG SELECT * FROM T_REPORT_CONFIG@DNET_LINK;
INSERT INTO T_REPORT_FILTER_DTL SELECT * FROM T_REPORT_FILTER_DTL@DNET_LINK;
INSERT INTO T_REPORT_FILTER_HDR SELECT * FROM T_REPORT_FILTER_HDR@DNET_LINK;
INSERT INTO T_REPORT_CONFIG_QUERY_SETTING SELECT * FROM T_REPORT_CONFIG_QUERY_SETTING@DNET_LINK;
INSERT INTO T_CONFIG_TAG SELECT * FROM T_CONFIG_TAG@DNET_LINK;

DELETE T_REPORT_VOUCHER_MAPPING MAP WHERE NOT EXISTS(SELECT 1 FROM T_CONFIG_FIXED_DATA SFD WHERE MAP.TRANS_TYPE_ID = SFD.CONFIG_ID);
DELETE T_REPORT_VOUCHER_MAPPING MAP WHERE NOT EXISTS(SELECT 1 FROM T_CONFIG_FIXED_DATA SFD WHERE MAP.TRANS_SUBTYPE_ID = SFD.CONFIG_ID);
UPDATE T_CONFIG_CLIENT_MASTER SET CATEGORY_ID = 0;
UPDATE T_DASHBOARD_CONFIG DT SET DASHBOARD_TYPE_ID = 0 WHERE NOT EXISTS(SELECT 1 FROM T_CONFIG_FIXED_DATA SFD WHERE DT.DASHBOARD_TYPE_ID = SFD.CONFIG_ID);
DELETE from T_CONFIG_FILTER_MAPPING MAP WHERE NVL(MAP.FORM_ID,0) >0  AND NOT EXISTS(SELECT 1 FROM T_CONFIG_FORM_MASTER SFD WHERE MAP.FORM_ID = SFD.FORM_ID);
DELETE FROM T_CONFIG_FILTER_MAPPING_DEFVAL DEF WHERE NOT EXISTS(SELECT 1 FROM T_CONFIG_FILTER_MAPPING SFD WHERE DEF.FILTER_MAPPING_ID = SFD.FILTER_MAPPING_ID);

COMMIT;

UPDATE T_CONFIG_QUERY_SETTING SET QRY_FILE_NAME = REPLACE(QRY_FILE_NAME,'.XML','.xml') WHERE QRY_FETCH_IND = 'F';
COMMIT;